import 'package:flutter/material.dart';
const bottomContainerHeight = 80.0;
const activeCardColour = Color(0xFF1D1E33);
const inactiveCardColour  = Color(0xFF111328);
const bottomContainerColour = Color(0xFFEB1555);
const labelTextStyle = TextStyle(fontSize: 18.0, color: Color(0xFF8D8E98));
const numberTextStyle = TextStyle(fontSize: 50.0 , fontWeight: FontWeight.w900,);
const largeButtonTextStyle = TextStyle(fontSize: 25.0,fontWeight: FontWeight.bold);
const titleTextStyle = TextStyle(fontSize: 50.0, fontWeight: FontWeight.bold);
const resultTextStyle = TextStyle(color: Color(0xFF24D876),fontWeight: FontWeight.bold,fontSize: 22.0);
const BMITextStyle = TextStyle(fontWeight: FontWeight.bold,fontSize: 100.0);
const bodyTextStyle = TextStyle(fontSize:22.0 );